version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      - POSTGRES_DB_FILE=/run/secrets/nextcloud_db
      - POSTGRES_USER_FILE=/run/secrets/nextcloud_db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/nextcloud_db_password
    secrets:
      - nextcloud_db
      - nextcloud_db_password
      - nextcloud_db_user


  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - data:/var/www/html
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/nextcloud_db_password
      - POSTGRES_DB_FILE=/run/secrets/nextcloud_db
      - POSTGRES_USER_FILE=/run/secrets/nextcloud_db_user
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.0.3
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - nextcloud_db
      - nextcloud_db_password
      - nextcloud_db_user

volumes:
  data:
  database:

secrets:
  nextcloud_admin_password:
    external: true
  nextcloud_admin_user:
    external: true
  nextcloud_db:
    external: true
  nextcloud_db_password:
    external: true
  nextcloud_db_user:
    external: true